[package]
name = "target-lexicon"
version = "0.0.3"
authors = ["Dan Gohman <sunfish@mozilla.com>"]
description = "Targeting utilities for compilers and related tools"
documentation = "https://docs.rs/target-lexicon/"
readme = "README.md"
keywords = ["target", "host", "triple", "compiler", "jit"]
categories = ["no-std"]
license = "Apache-2.0 WITH LLVM-exception"
repository = "https://github.com/cretonne/target-lexicon"

[dependencies]
failure = { version = "0.1.1", default-features = false, features = ["derive"] }
failure_derive = { version = "0.1.1", default-features = false }

[build-dependencies]
serde_json = "1.0"

[features]
default = ["std"]
std = []

[badges]
maintenance = { status = "passively-maintained" }
travis-ci = { repository = "cretonne/target-lexicon" }
